spring:
  flyway:
    baseline-on-migrate: true
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/movie
    username: glaze
    password: dalmatian
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
