spring:
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/testing
    username: glaze
    password: dalmatian
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
