name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  QA:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Run quality checks
        run: ./gradlew checkstyleMain checkstyleTest pmdMain pmdTest

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Run tests
        run: ./gradlew test

  pusblish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - QA
      - test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Push to docker hub
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE: ${{ secrets.DOCKER_IMAGE }}
        run: |
          ./gradlew jib \
          -Djib.to.auth.username = $USERNAME \
          -Djib.to.auth.password = $PASSWORD \
          -Djib.to.image = $IMAGE
